# Generated by Django 4.2.17 on 2024-12-18 01:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("last_full_refresh", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("institution_name", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Afghanistan", "Afghanistan"),
                            ("Albania", "Albania"),
                            ("Algeria", "Algeria"),
                            ("Andorra", "Andorra"),
                            ("Angola", "Angola"),
                            ("Antigua and Barbuda", "Antigua and Barbuda"),
                            ("Argentina", "Argentina"),
                            ("Armenia", "Armenia"),
                            ("Australia", "Australia"),
                            ("Austria", "Austria"),
                            ("Azerbaijan", "Azerbaijan"),
                            ("Bahamas", "Bahamas"),
                            ("Bahrain", "Bahrain"),
                            ("Bangladesh", "Bangladesh"),
                            ("Barbados", "Barbados"),
                            ("Belarus", "Belarus"),
                            ("Belgium", "Belgium"),
                            ("Belize", "Belize"),
                            ("Benin", "Benin"),
                            ("Bhutan", "Bhutan"),
                            ("Bolivia", "Bolivia"),
                            ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
                            ("Botswana", "Botswana"),
                            ("Brazil", "Brazil"),
                            ("Brunei", "Brunei"),
                            ("Bulgaria", "Bulgaria"),
                            ("Burkina Faso", "Burkina Faso"),
                            ("Burundi", "Burundi"),
                            ("Cabo Verde", "Cabo Verde"),
                            ("Cambodia", "Cambodia"),
                            ("Cameroon", "Cameroon"),
                            ("Canada", "Canada"),
                            ("Central African Republic", "Central African Republic"),
                            ("Chad", "Chad"),
                            ("Chile", "Chile"),
                            ("China", "China"),
                            ("Colombia", "Colombia"),
                            ("Comoros", "Comoros"),
                            (
                                "Congo, Democratic Republic of the",
                                "Congo, Democratic Republic of the",
                            ),
                            ("Congo, Republic of the", "Congo, Republic of the"),
                            ("Costa Rica", "Costa Rica"),
                            ("Croatia", "Croatia"),
                            ("Cuba", "Cuba"),
                            ("Cyprus", "Cyprus"),
                            ("Czechia", "Czechia"),
                            ("Denmark", "Denmark"),
                            ("Djibouti", "Djibouti"),
                            ("Dominica", "Dominica"),
                            ("Dominican Republic", "Dominican Republic"),
                            ("Ecuador", "Ecuador"),
                            ("Egypt", "Egypt"),
                            ("El Salvador", "El Salvador"),
                            ("Equatorial Guinea", "Equatorial Guinea"),
                            ("Eritrea", "Eritrea"),
                            ("Estonia", "Estonia"),
                            ("Eswatini", "Eswatini"),
                            ("Ethiopia", "Ethiopia"),
                            ("Fiji", "Fiji"),
                            ("Finland", "Finland"),
                            ("France", "France"),
                            ("Gabon", "Gabon"),
                            ("Gambia", "Gambia"),
                            ("Georgia", "Georgia"),
                            ("Germany", "Germany"),
                            ("Ghana", "Ghana"),
                            ("Greece", "Greece"),
                            ("Grenada", "Grenada"),
                            ("Guatemala", "Guatemala"),
                            ("Guinea", "Guinea"),
                            ("Guinea-Bissau", "Guinea-Bissau"),
                            ("Guyana", "Guyana"),
                            ("Haiti", "Haiti"),
                            ("Honduras", "Honduras"),
                            ("Hungary", "Hungary"),
                            ("Iceland", "Iceland"),
                            ("India", "India"),
                            ("Indonesia", "Indonesia"),
                            ("Iran", "Iran"),
                            ("Iraq", "Iraq"),
                            ("Ireland", "Ireland"),
                            ("Israel", "Israel"),
                            ("Italy", "Italy"),
                            ("Jamaica", "Jamaica"),
                            ("Japan", "Japan"),
                            ("Jordan", "Jordan"),
                            ("Kazakhstan", "Kazakhstan"),
                            ("Kenya", "Kenya"),
                            ("Kiribati", "Kiribati"),
                            ("Korea, North", "Korea, North"),
                            ("Korea, South", "Korea, South"),
                            ("Kosovo", "Kosovo"),
                            ("Kuwait", "Kuwait"),
                            ("Kyrgyzstan", "Kyrgyzstan"),
                            ("Laos", "Laos"),
                            ("Latvia", "Latvia"),
                            ("Lebanon", "Lebanon"),
                            ("Lesotho", "Lesotho"),
                            ("Liberia", "Liberia"),
                            ("Libya", "Libya"),
                            ("Liechtenstein", "Liechtenstein"),
                            ("Lithuania", "Lithuania"),
                            ("Luxembourg", "Luxembourg"),
                            ("Madagascar", "Madagascar"),
                            ("Malawi", "Malawi"),
                            ("Malaysia", "Malaysia"),
                            ("Maldives", "Maldives"),
                            ("Mali", "Mali"),
                            ("Malta", "Malta"),
                            ("Marshall Islands", "Marshall Islands"),
                            ("Mauritania", "Mauritania"),
                            ("Mauritius", "Mauritius"),
                            ("Mexico", "Mexico"),
                            ("Micronesia", "Micronesia"),
                            ("Moldova", "Moldova"),
                            ("Monaco", "Monaco"),
                            ("Mongolia", "Mongolia"),
                            ("Montenegro", "Montenegro"),
                            ("Morocco", "Morocco"),
                            ("Mozambique", "Mozambique"),
                            ("Myanmar", "Myanmar"),
                            ("Namibia", "Namibia"),
                            ("Nauru", "Nauru"),
                            ("Nepal", "Nepal"),
                            ("Netherlands", "Netherlands"),
                            ("New Zealand", "New Zealand"),
                            ("Nicaragua", "Nicaragua"),
                            ("Niger", "Niger"),
                            ("Nigeria", "Nigeria"),
                            ("North Macedonia", "North Macedonia"),
                            ("Norway", "Norway"),
                            ("Oman", "Oman"),
                            ("Pakistan", "Pakistan"),
                            ("Palau", "Palau"),
                            ("Palestine", "Palestine"),
                            ("Panama", "Panama"),
                            ("Papua New Guinea", "Papua New Guinea"),
                            ("Paraguay", "Paraguay"),
                            ("Peru", "Peru"),
                            ("Philippines", "Philippines"),
                            ("Poland", "Poland"),
                            ("Portugal", "Portugal"),
                            ("Qatar", "Qatar"),
                            ("Romania", "Romania"),
                            ("Russia", "Russia"),
                            ("Rwanda", "Rwanda"),
                            ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
                            ("Saint Lucia", "Saint Lucia"),
                            (
                                "Saint Vincent and the Grenadines",
                                "Saint Vincent and the Grenadines",
                            ),
                            ("Samoa", "Samoa"),
                            ("San Marino", "San Marino"),
                            ("Sao Tome and Principe", "Sao Tome and Principe"),
                            ("Saudi Arabia", "Saudi Arabia"),
                            ("Senegal", "Senegal"),
                            ("Serbia", "Serbia"),
                            ("Seychelles", "Seychelles"),
                            ("Sierra Leone", "Sierra Leone"),
                            ("Singapore", "Singapore"),
                            ("Slovakia", "Slovakia"),
                            ("Slovenia", "Slovenia"),
                            ("Solomon Islands", "Solomon Islands"),
                            ("Somalia", "Somalia"),
                            ("South Africa", "South Africa"),
                            ("South Sudan", "South Sudan"),
                            ("Spain", "Spain"),
                            ("Sri Lanka", "Sri Lanka"),
                            ("Sudan", "Sudan"),
                            ("Suriname", "Suriname"),
                            ("Sweden", "Sweden"),
                            ("Switzerland", "Switzerland"),
                            ("Syria", "Syria"),
                            ("Taiwan", "Taiwan"),
                            ("Tajikistan", "Tajikistan"),
                            ("Tanzania", "Tanzania"),
                            ("Thailand", "Thailand"),
                            ("Timor-Leste", "Timor-Leste"),
                            ("Togo", "Togo"),
                            ("Tonga", "Tonga"),
                            ("Trinidad and Tobago", "Trinidad and Tobago"),
                            ("Tunisia", "Tunisia"),
                            ("Turkey", "Turkey"),
                            ("Turkmenistan", "Turkmenistan"),
                            ("Tuvalu", "Tuvalu"),
                            ("Uganda", "Uganda"),
                            ("Ukraine", "Ukraine"),
                            ("United Arab Emirates", "United Arab Emirates"),
                            ("United Kingdom", "United Kingdom"),
                            ("United States", "United States"),
                            ("Uruguay", "Uruguay"),
                            ("Uzbekistan", "Uzbekistan"),
                            ("Vanuatu", "Vanuatu"),
                            ("Vatican City", "Vatican City"),
                            ("Venezuela", "Venezuela"),
                            ("Vietnam", "Vietnam"),
                            ("Yemen", "Yemen"),
                            ("Zambia", "Zambia"),
                            ("Zimbabwe", "Zimbabwe"),
                        ],
                        max_length=255,
                    ),
                ),
                ("nordigen_code", models.UUIDField(blank=True, null=True)),
                ("color", models.CharField(default="#4b8dd3", max_length=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "balance",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "code",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=127)),
                ("symbol", models.CharField(blank=True, max_length=7, null=True)),
                ("is_liquid", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "name",
                    models.CharField(max_length=63, primary_key=True, serialize=False),
                ),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entity", models.CharField(max_length=255)),
                (
                    "amount",
                    models.FloatField(
                        validators=[main.models.Transaction.validate_transaction_amount]
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("category", models.CharField(blank=True, max_length=31, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.account"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.asset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.FloatField(
                        validators=[main.models.Trade.validate_trade_amount]
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.account"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_asset",
                        to="main.asset",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counter_asset",
                        to="main.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "balance",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "account_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.accountitem",
                    ),
                ),
            ],
            options={
                "ordering": ["account_item", "date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.assetclass"
            ),
        ),
        migrations.AddField(
            model_name="accountitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.asset"
            ),
        ),
        migrations.AddConstraint(
            model_name="balancehistory",
            constraint=models.UniqueConstraint(
                fields=("account_item", "date"), name="unique_accountitem_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountitem",
            constraint=models.UniqueConstraint(
                fields=("account", "asset"), name="unique_account_asset_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("institution_name", "user"), name="unique_institution_name_user"
            ),
        ),
    ]
